class MultiplicatorUnitFailure extends Error {}

function primitiveMultiply(a, b) {
  if (Math.random() < 0.2) {
    return a * b;
  } else {
    throw new MultiplicatorUnitFailure("Klunk");
  }
}

function reliableMultiply(a, b) {
  while(true){
    try{
      const value = primitiveMultiply(a, b);
      return value;
    }
    catch(e) {
      if (!e instanceof MultiplicatorUnitFailure) throw e;
    }
  }
}

console.log(reliableMultiply(8, 8));
// â†’ 64